name: 'Test oasdiff actions'
on:
  push:
jobs:
  oasdiff_diff:
    runs-on: ubuntu-latest
    name: Test diff action
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Checking OpenAPI Spec changes
        uses: ./breaking
        with:
          base: 'specs/petstore-base.yaml'
          revision: 'specs/petstore-revision.yaml'
          fail-on-diff: false