name: 'Test oasdiff actions'
on:
  pull_request:
  push:
jobs:
  oasdiff_diff:
    runs-on: ubuntu-latest
    name: Test diff action
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Checking OpenAPI Spec changes
        uses: oasdiff/oasdiff-action/breaking@v0.0.18
        with:
          base: 'specs/petstore-base.yaml'
          revision: 'specs/petstore-revision.yaml'